routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

//Route::get('/home', function () {
//    return Inertia::render('Welcome', [
//        'canLogin' => Route::has('login'),
//        'laravelVersion' => Application::VERSION,
//        'phpVersion' => PHP_VERSION,
//    ]);
//});

Route::get('/aboutNew', function () {
    return Inertia::render('FrontendPages/About');
});

//Route::get('/dashboard', function () {
//    return Inertia::render('Dashboard');
//})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

//Front-end links
Route::get('/', 'PagesController@index')->name('home');
Route::get('/about', 'PagesController@about');
Route::post('/events', 'PagesController@getEventsByFilters');
Route::post('/events/register', 'Events\EventsController@registerEventUser');
Route::get('/red-sails', 'RedSailsController@showFestivalOverview');
Route::get('/red-sails/{date}', 'RedSailsController@showProgrammeForDay');
Route::get("/log-in", 'Auth\LoginController@index')->name("log-in");

//News page links
Route::group(['prefix' => 'news'], function() {
    Route::get('/', 'PagesController@news');
    Route::post('/', 'PagesController@getNewsByFilters');
    Route::get('/story/{id}', 'PagesController@showNewsStory');
});

//Events page links
Route::group(['prefix' => 'event'], function() {
    Route::get('/', 'PagesController@events');
    Route::get('/{id}', 'PagesController@showEvent');
    Route::post('/register/guest', 'MailSend@registerEventGuest');
    Route::get('/register/guest', 'MailSend@showRegisterEventGuest');
});

Route::get('/contact-us', 'PagesController@contact');
Route::post('/contact-submit', 'MailSend@contact_us');
Route::post('/subscribe', 'MailSend@subscribe');
Route::get('sub/verify/{token?}', 'MailSend@verified');
Route::get('event/verify/{token?}', 'MailSend@eventVerified');
Route::post('/event/reg/confirm', 'MailSend@validateEventToken');
Route::get('/event/register/cancel/{id?}', 'MailSend@cancelEventRegGuest');
Route::post('/user/create/setPassword/{id}', 'PagesController@createUserPassword');

//Auth Routes
Auth::routes(['verify' => true]);
Route::get('/register', 'PagesController@register');
Route::get('/login', function() {
    return redirect("/log-in");
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('/users/resetPass', 'Admin\UsersController@displayResetUserPassword');
    Route::get('/user/profile', 'AccountsController@profile');
    Route::post('/user/profile', 'AccountsController@storeProfile');
    Route::post('/user/profile/update', 'AccountsController@updateProfile');
    Route::post('/user/profile/delete/{id}', 'AccountsController@deleteAccount');
    Route::get('/user/profile/create', 'AccountsController@createProfile');
});

//Member links
Route::post('/policy/download/{filename}', 'PoliciesController@downloadFile')->middleware('auth', 'can:view-policy');
Route::get('/policies', 'MemberController@viewPolicies')->middleware('auth', 'can:view-policy');

//Event Manager Links
Route::namespace('Events')->prefix('events')->name('events.')->middleware('auth', 'can:manage-events')->group(function(){
    Route::get('/index', 'EventsController@index')->name('event');
    Route::get('/edit/{id}', 'EventsController@edit')->name('event-edit');
    Route::put('/edit/{id}', 'EventsController@update');
    Route::get('/registered/{id}', 'EventsController@showRegistered');
    Route::get('/create', 'EventsController@create');
    Route::post('/create', 'EventsController@store');
    Route::post('/delete', 'EventsController@destroy');
    Route::get('/photo_upload/{id}', 'EventsController@showUploadImages');
    Route::post('/photo_upload/{id}', 'EventsController@uploadImages');
    Route::post('/delete_photos/{id}', 'EventsController@deleteImages');
    Route::post('/search', 'EventsController@searchEvents');
});

//User links
Route::group(['prefix' => 'user'], function () {
    Route::get('/events', 'AccountsController@events')->middleware('auth', 'can:view-policy');
    Route::get('/committees/{id}', 'AccountsController@showCommittees')->middleware('auth', 'can:view-policy');
    Route::put('/committees/update/{id}', 'Admin\UsersController@updateUserCauses')->middleware('auth', 'can:manage-users')->name('user.committees.update');
    Route::get('/create/verify/{token?}', 'MailSend@validateUserToken');
});

Route::delete('cancel_reg/{id}', [
    'uses' => 'AccountsController@cancelReg'
])->middleware('auth');

//Author links
Route::namespace('News')->prefix('news')->name('news.')->middleware('auth', 'can:manage-news')->group(function(){
    Route::get('/index', 'NewsController@index');
    Route::get('/edit/{id}', 'NewsController@edit')->name('edit-news');
    Route::put('/edit/{id}', 'NewsController@update')->name('news-update');
    Route::get('/create', 'NewsController@create');
    Route::post('/create', 'NewsController@store');
    Route::post('/delete', 'NewsController@destroy');
    Route::post('/search', 'NewsController@searchNews');
});

//Admin links
Route::group(['middleware' => 'auth', 'middleware' => 'can:manage-users', 'prefix' => 'admin'], function() {
    Route::get('/contact', 'ContactController@index');
    Route::get('/userstest', 'Admin\UsersController@brdindex');
    Route::get('/dashboard', 'DashboardsController@admin');
    Route::post('users/processResetPass', 'Admin\UsersController@resetUserPassword');
    Route::get('/getContactMessages', 'ContactController@getMessages');
    Route::post('/users/getByFilter', 'Admin\UsersController@getUsersByFilters');
    Route::post('/getUserCauses', 'Admin\UsersController@getUserCauses');
    Route::get('/getCommitteeGrowth', 'DashboardsController@getCommitteeGrowth');
    Route::get('/getSiteTraffic', 'DashboardsController@getSiteTraffic');
    Route::get('/contact/reply/{id}', 'ContactController@show');
    Route::post('/contact/reply/{id}', 'MailSend@contact_response');
    Route::post('/contact/close', 'ContactController@closeRequest');
    Route::post('/contact/flipToRead', 'ContactController@flipToRead');
    Route::post('/contact/flipToUnread', 'ContactController@flipToUnread');
    Route::post('/contact/delete', 'ContactController@destroy');
    Route::post('/contact/filter', 'ContactController@filter');
    Route::get('/events/applications', 'ApproveController@eventApplications');
    Route::post('/events/approve', 'ApproveController@approveEvent');
    Route::post('/events/amendApp', 'ApproveController@amendAppSubmit');
    Route::delete('/events/rejectApp/{id}', 'ApproveController@rejectApp');
    Route::get('/events/amend-application/{id}', 'ApproveController@amendApp');
    Route::post('/users/createNew', 'MailSend@createdUserReg');
});
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['show']]);
    Route::post('/users/search', 'UsersController@searchUser');
    Route::get('/users/resetPass', 'UsersController@displayResetUserPassword');
    Route::get('/users/{id}/edit', 'UsersController@edit');
});

//Policy links
Route::get('/policy-docs', 'PoliciesController@index')->middleware('auth', 'can:manage-users');
Route::post('/policy/upload', 'PoliciesController@store')->middleware('auth', 'can:manage-users');
Route::get('/policy/download/{filename}', 'PoliciesController@downloadFile')->name('downloadFile')->middleware('auth', 'can:manage-users');
Route::post('/policy/delete/{filename}', 'PoliciesController@destroy')->middleware('auth', 'can:manage-users');


require __DIR__.'/auth.php';

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'roles' => 'array',
        'causes' => 'array'
    ];

    public function hasRole($role) {
        if($this->roles()->where('name', $role)->first()) {
        return true;
    }
    return false;
    }

    public function roles() {
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles) {
        if($this->roles()->whereIn('name', $roles)->first()) {
        return true;
    }
    return false;
}

    public function assignRole(Role $role)
    {
    return $this->roles()->save($role);
    }

    public function causes()
    {
        return $this->belongsToMany('App\Cause');
    }

    public function hasCause($cause)
    {
        if($this->causes()->where('name', $cause)->first()) {
            return true;
        }
        return false;
    }
    public function hasAnyCauses($causes)
    {
        if($this->roles()->whereIn('name', $causes)->first()) {
            return true;
        }
        return false;
    }

    public function assignCause(Cause $cause)
    {
        return $this->cause()->save($cause);
    }

    public function profile() {
        return $this->hasOne('App\Profile');
    }
}

resources/views/admin/users/create.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
      $(document).ready(function(){
        $('#toggle-sidenav').on('click', function(){
          $('.sidenav-holder').toggle();
          $('.content-holder').toggleClass('col-lg-10').toggleClass('col-lg-12');
        });
      });
        </script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<div id="app">
    <div class="container-fluid" style="text-align: left; color: #000;">
      <div class="row no-gutters">
        <div class="sidenav-holder col-12 col-lg-2">
          @include('inc.admin-sidenav')
        </div>
        <div class="content-holder col-12 col-lg-10">
          @include('inc.admin-nav')
<div id="create-user">
  @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
    @include('partials.alerts')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">Create New User</div>
    
                    <div class="card-body">
                        
                      <form action="/admin/users/createNew" method="POST">
                        @csrf   
                        <div class="form-group row">
                            <label for="email" class="col-12 col-form-label">Email: <span class="asterisk">*</span></label>
    
                            <div class="col-12">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" required>
    
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{$message}}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="roles" class="col-form-label">Roles <span class="asterisk">*</span> <br>(Please select at least one)</label>
                            <div class="col-12">
                        @foreach ($roles as $role)
                            <div class="form-check">
                              <input type="checkbox" name="roles[]" value="{{ $role->id }}" class="@error('roles') is-invalid @enderror">
                              @error('roles')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{$message}}</strong>
                                    </span>
                                @enderror
                              <label>{{ $role->name }}</label>
                            </div>
                        @endforeach
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Create User</button>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/admin/users/edit.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    $('#toggle-sidenav').on('click', function(){
      $('.sidenav-holder').toggle();
      $('.content-holder').toggleClass('col-lg-10').toggleClass('col-lg-12');
    });
  });
    </script>
</head>
<div id="app">
    <div class="container-fluid" style="text-align: left; color: #000;">
      <div class="row no-gutters">
        <div class="sidenav-holder col-12 col-lg-2">
          @include('inc.admin-sidenav')
        </div>
        <div class="content-holder col-12 col-lg-10">
          @include('inc.admin-nav')
<div class="container">
  <div id="edit-user">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @php
            try {
                $firstNameString = decrypt(strval($user->profile()->pluck('firstname')));
                $lastNameString = decrypt(strval($user->profile()->pluck('surname')));
            } catch (Exception $e) {
            }
            @endphp
            <div class="card">
                <div class="card-header">Edit User Roles for {{$firstNameString}} {{$lastNameString}}</div>

                <div class="card-body">

                  <form action="{{route('admin.users.update', $user)}}" method="POST">
                    @csrf
                    {{ method_field('PUT') }}

                    <div class="form-group row">
                        <label for="roles" class="col-md-2 col-form-label text-md-right">Roles</label>

                        <div class="col-md-6">
                    @foreach ($roles as $role)
                        <div class="form-check">
                          <input type="checkbox" name="roles[]" value="{{ $role->id }}"
                          @if($user->roles()->pluck('id')->contains($role->id)) checked @endif>
                          <label>{{ $role->name }}</label>
                        </div>
                    @endforeach
                    </div>
                </div>
                <div class="row">
                  <div class="col-10">
                <a href="/admin/users"><button type="button" class="btn btn-secondary">Cancel</button></a>
              </div>
              <div class="col-2">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Update</button>
                  </div>
                  </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

resources/views/admin/users/index.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                          <script>
                            $(document).ready(function(){

                          $('#toggle-sidenav').on('click', function(){
      $('.sidenav-holder').toggle();
      $('.content-holder').toggleClass('col-lg-10').toggleClass('col-lg-12');
    });
                        });

                      </script>
</head>
<body>
  <div id="app">
<div class="container-fluid" style="text-align: left; color: #000;">
  <div class="row no-gutters">
    <div class="sidenav-holder col-12 col-lg-2">
      @include('inc.admin-sidenav')
    </div>
    <div class="content-holder col-12 col-lg-10">
      @include('inc.admin-nav')
      <div id="manage-users">
        @include('partials.alerts')
        <div class="row justify-content-center">
          <div class="col-12">
          <div class="card">
            <div class="card-header">User Management</div>
            <p class="mob-info pt-5">Scroll right to see more</p>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-sm" id="user-table">
                      <span id="total_records"></span>
                        <thead class="thead-dark">
                          <tr class="d-flex">
                            <th scope="col" class="manage-users-name col-6 col-lg-2">Name</th>
                            <th scope="col" class="manage-users-email col-6 col-lg-3">Email</th>
                            <th scope="col" class="manag-users-roles col-6 col-lg-3">Roles</th>
                            <th scope="col" class="manage-users-actions text-center col-6 col-lg-4">Actions</th>
                          </tr>
                        </thead>
                        <thead class="thead">
                          <tr class="d-flex">
{{--                            <th scope="col-12" class="manage-users-name col-12"><form action="/admin/users/search" method="POST">--}}
{{--                              @csrf<input type="text" placeholder="Search Name" name="name" class="col-8">--}}
{{--                            </div>--}}
{{--                            <button type="submit" class="btn btn-primary col-3 ml-5">Search</button>--}}
{{--                        </th>--}}
{{--                          </form>--}}
{{--                        </div>--}}
                          </tr>
                        </thead>
                        <tbody>
{{--                </div>--}}
          </div>
  <!-- Modal -->
  @foreach($users as $u)
              @php
                 $firstNameString = decrypt(strval($u->profile()->pluck('firstname')));
                 $lastNameString = decrypt(strval($u->profile()->pluck('surname')));
              @endphp
                    <tr class="d-flex">
                      <td class="col-6 col-lg-2">{{$firstNameString}} {{$lastNameString}}</td>
                        <td class="col-6 col-lg-3">{{$u->email}}</td>
                        <td class="col-6 col-lg-3">{{implode(", ", $u->roles()->pluck('name')->toArray())}}</td>
                        <td id="action-buttons" class="text-center col-6 col-lg-4">
                          <button id="view-user{{$u->id}}" type="submit" class="btn btn-success " value="{{$u->id}}" data-toggle="modal" data-target="#view{{$u->id}}"><img src="/img/baseline_visibility_white_18dp.png" data-toggle="tooltip" data-placement="bottom" title="View User Details"></button>
                          <button id="comms-user{{$u->id}}" type="submit" class="btn btn-dark " value="{{$u->id}}" data-toggle="modal" data-target="#comms{{$u->id}}"><img src="/img/baseline_people_alt_white_18dp.png" data-toggle="tooltip" data-placement="bottom" title="User Committees"></button>
                          <a href="{{route('admin.users.edit', $u->id)}}"><button type="button" class="btn btn-dark "><img src="/img/baseline_create_white_18dp.png" data-toggle="tooltip" data-placement="bottom" title="Edit User Roles"></button></a>
                                <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#delete{{$u->id}}"><img src="/img/baseline_delete_white_18dp.png" data-toggle="tooltip" data-placement="bottom" title="Delete User"></button>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                      </table>
{{--                      {!! $users->render() !!}--}}
                    </div>
                    </div>
            </div>
            </div>
{{--            <div class="render">--}}
{{--            </div>--}}
        </div>
    </div>
</div>
</div>
{{--</div>--}}
@foreach($users as $user)
    @php
        try {
        $firstNameString = decrypt(strval($user->profile()->pluck('firstname')));
        $lastNameString = decrypt(strval($user->profile()->pluck('surname')));
        $addressString = decrypt(strval($user->profile()->pluck('address')));
        $townString = decrypt(strval($user->profile()->pluck('town')));
        $postcodeString = decrypt(strval($user->profile()->pluck('postcode')));
        $contactNoString = decrypt(strval($user->profile()->pluck('contact_no')));
        } catch (Exception $e) {
        }
    @endphp
<!-- View Modal -->
<div class="modal fade" id="view{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">User Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3><strong>Name:</strong> {{$firstNameString}} {{$lastNameString}}</h3>
        <h3><strong>Address:</strong> {{$addressString}}
        <h3><strong>Town:</strong> {{$townString}}</h3>
        <h3><strong>Postcode:</strong> {{$postcodeString}}</h3>
        <h3><strong>Contact No:</strong> {{$contactNoString}}</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="comms{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">User Committies</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/user/committees/update/{{$user->id}}" method="POST">
          {{ method_field('PUT') }}
          @csrf
          <div class="form-group row">
            <div class="row">
            @foreach($causes as $cause)
            <div class="form-check col-6">
                <input type="checkbox" name="comms[]" value="{{ $cause->id }}"
                @if($user->causes()->pluck('id')->contains($cause->id)) checked @endif>
                <label>{{ $cause->name }}</label>
              </div>
            @endforeach
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Save</button>
      </form>
      </div>
    </div>
  </div>
</div>

  <!-- Delete Modal -->
  <div class="modal fade" id="delete{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Confirm Delete User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          This will delete the user {{$firstNameString}} {{$lastNameString}}. Are you sure you wish to delete this user?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="/users/{{$user->id}}" method="POST">
                {{ method_field('DELETE') }}
                @csrf
                <input type="hidden" value="{{$user->id}}"/>
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
{{--          {!! Form::open(['action' => ['Admin\UsersController@destroy', $user->id], 'method' => 'POST', 'class' => 'pull-right']) !!}--}}
{{--          {{Form::hidden('_method', 'DELETE')}}--}}
{{--          {{Form::submit('Delete', ['class' => 'btn btn-danger'])}}--}}
{{--          {!!Form::close()!!}--}}
        </div>
      </div>
    </div>
  </div>
</div>
@endforeach
</body>
</html>